### ISSUE TITLE
flask-migrate执行migrate命令出现问题

### ISSUE THREAD

**Issue by hippoKnight** [wodaomaimaiti/flasky-Learing#6]
```
# manage.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))

if __name__ == '__main__':
    manager.run()
```

先不db.create_all()直接init, migrate, 能加入表user, 但无法向db中插入数据
```
(myvenv) tdss@tdss-virtual-machine:~/dbtest$ python manage.py db init
  Creating directory /home/tdss/dbtest/migrations ... done
  Creating directory /home/tdss/dbtest/migrations/versions ... done
  Generating /home/tdss/dbtest/migrations/script.py.mako ... done
  Generating /home/tdss/dbtest/migrations/alembic.ini ... done
  Generating /home/tdss/dbtest/migrations/env.py ... done
  Generating /home/tdss/dbtest/migrations/README ... done
  Please edit configuration/connection/logging settings in
  '/home/tdss/dbtest/migrations/alembic.ini' before proceeding.
(myvenv) tdss@tdss-virtual-machine:~/dbtest$ python manage.py db migrate
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'
  Generating /home/tdss/dbtest/migrations/versions/2604cd6546c2_.py ... done
(myvenv) tdss@tdss-virtual-machine:~/dbtest$ python manage.py shell
>>> from manage import db ,User
>>> u= User(name='asdf')
>>> db.session.add(u)
>>> db.session.commit()
Traceback (most recent call last):
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/tdss/myvenv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'INSERT INTO user (name) VALUES (?)'] [parameters: ('asdf',)]


```
先db.create_all()，再插入数据，再init, migrate,  则无法迁移
  
```
(myvenv) tdss@tdss-virtual-machine:~/dbtest$ python manage.py db migrate
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
```

**Comment by hippoKnight** [comment]
书上说自动迁移可能出错，不知与此是否相关
![image](https://cloud.githubusercontent.com/assets/6011391/26762078/46ceb3e6-496e-11e7-9c2d-27dba04a69f1.png)
